services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "8080:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_bank
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data