name: ci-test

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: simple_bank
                ports:
                    - 8080:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: 1.20
            - name: Run test
              run: make test